const REF=new Date(2026,6,6),cycle=[2,1,3];let baseShift=Number(localStorage.getItem('baseShift'))||0;
const picker=document.getElementById('datePicker'),cal=document.getElementById('calendar'),setup=document.getElementById('setup');let view=new Date();view.setDate(1);
const pad=n=>String(n).padStart(2,'0'),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
function monday(d){let x=new Date(d.getFullYear(),d.getMonth(),d.getDate()),q=x.getDay();x.setDate(x.getDate()-(q===0?6:q-1));return x}
function shift(d){if(d.getDay()===0)return 0;let w=Math.round((monday(d)-REF)/604800000),idx=cycle.indexOf(baseShift);return cycle[((idx+w)%3+3)%3]}
function show(d){picker.value=iso(d);let s=shift(d),b=document.getElementById('shiftBadge');b.className='badge '+(s?'shift'+s:'sunday');b.textContent=s?s+'°':'☕';document.getElementById('shiftTitle').textContent=s?`${s}° turno`:'Riposo';document.getElementById('shiftInfo').textContent=d.toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'});render()}
function render(){cal.innerHTML='';document.getElementById('monthTitle').textContent=view.toLocaleDateString('it-IT',{month:'long',year:'numeric'});let f=(view.getDay()+6)%7,n=new Date(view.getFullYear(),view.getMonth()+1,0).getDate();for(let i=0;i<f;i++){let e=document.createElement('span');e.className='day empty';cal.append(e)}for(let i=1;i<=n;i++){let d=new Date(view.getFullYear(),view.getMonth(),i),s=shift(d),b=document.createElement('button');b.className='day '+(s?'shift'+s:'sunday');if(iso(d)===picker.value)b.classList.add('selected');if(iso(d)===iso(new Date()))b.classList.add('today');b.innerHTML=`${i}<small>${s?s+'°':'R'}</small>`;b.onclick=()=>show(d);cal.append(b)}}
document.querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>{baseShift=Number(b.dataset.shift);localStorage.setItem('baseShift',baseShift);setup.classList.add('hidden');show(new Date())});
document.getElementById('settings').onclick=()=>setup.classList.remove('hidden');
document.getElementById('prev').onclick=()=>{view.setMonth(view.getMonth()-1);render()};document.getElementById('next').onclick=()=>{view.setMonth(view.getMonth()+1);render()};
picker.onchange=()=>{let [y,m,d]=picker.value.split('-').map(Number),x=new Date(y,m-1,d);view=new Date(y,m-1,1);show(x)};
let now=new Date();document.getElementById('today').textContent=now.toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long'});if(!baseShift)setup.classList.remove('hidden');else show(now);
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');