const cycle=[3,2,1];let baseShift=Number(localStorage.getItem('baseShift'))||0;let savedRef=localStorage.getItem('referenceMonday');let REF=savedRef?new Date(savedRef+'T12:00:00'):null;
const picker=document.getElementById('datePicker'),cal=document.getElementById('calendar'),setup=document.getElementById('setup');let view=new Date();view.setDate(1);
const pad=n=>String(n).padStart(2,'0'),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
function monday(d){let x=new Date(d.getFullYear(),d.getMonth(),d.getDate()),q=x.getDay();x.setDate(x.getDate()-(q===0?6:q-1));return x}
function shift(d){if(d.getDay()===0)return 0;let w=Math.round((monday(d)-REF)/604800000),idx=cycle.indexOf(baseShift);return cycle[((idx+w)%3+3)%3]}
function show(d){picker.value=iso(d);let s=shift(d),b=document.getElementById('shiftBadge');b.className='badge '+(s?'shift'+s:'sunday');b.textContent=s?s+'°':'☕';document.getElementById('shiftTitle').textContent=s?`${s}° turno`:'Riposo';document.getElementById('shiftInfo').textContent=d.toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'});render()}
function render(){cal.innerHTML='';document.getElementById('monthTitle').textContent=view.toLocaleDateString('it-IT',{month:'long',year:'numeric'});let f=(view.getDay()+6)%7,n=new Date(view.getFullYear(),view.getMonth()+1,0).getDate();for(let i=0;i<f;i++){let e=document.createElement('span');e.className='day empty';cal.append(e)}for(let i=1;i<=n;i++){let d=new Date(view.getFullYear(),view.getMonth(),i),s=shift(d),b=document.createElement('button');let ev=events[iso(d)];b.className='day '+(ev|| (s?'shift'+s:'sunday'));if(iso(d)===picker.value)b.classList.add('selected');if(iso(d)===iso(new Date()))b.classList.add('today');b.innerHTML=`${i}<small>${s?s+'°':'R'}</small>`;b.onclick=()=>openDay(d,s);cal.append(b)}}
document.querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>{baseShift=Number(b.dataset.shift);REF=monday(new Date());localStorage.setItem('baseShift',baseShift);localStorage.setItem('referenceMonday',iso(REF));setup.classList.add('hidden');view=new Date();view.setDate(1);show(new Date())});
document.getElementById('settings').onclick=()=>setup.classList.remove('hidden');
document.getElementById('prev').onclick=()=>{view.setMonth(view.getMonth()-1);render()};document.getElementById('next').onclick=()=>{view.setMonth(view.getMonth()+1);render()};
picker.onchange=()=>{let [y,m,d]=picker.value.split('-').map(Number),x=new Date(y,m-1,d);view=new Date(y,m-1,1);show(x)};
let now=new Date();document.getElementById('today').textContent=now.toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long'});if(!baseShift||!REF)setup.classList.remove('hidden');else show(now);
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');
let layoutTimer;
function refreshLayout(){clearTimeout(layoutTimer);layoutTimer=setTimeout(()=>{document.documentElement.style.width='100%';document.body.style.width='100%';render()},300)}
window.addEventListener('orientationchange',refreshLayout);
window.addEventListener('resize',refreshLayout);

function openDay(d,s){selectedDay=iso(d);document.getElementById('modalDate').textContent=d.toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'});document.getElementById('modalPlanned').textContent='Turno previsto: '+(s?s+'° turno':'Riposo');document.getElementById('dayModal').classList.remove('hidden')}
document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{if(b.dataset.event)events[selectedDay]=b.dataset.event;else delete events[selectedDay];localStorage.setItem('shiftEvents',JSON.stringify(events));document.getElementById('dayModal').classList.add('hidden');render();updateStats()});
document.getElementById('closeModal').onclick=()=>document.getElementById('dayModal').classList.add('hidden');
let statsYear=document.getElementById('statsYear'),currentYear=new Date().getFullYear();for(let y=currentYear-3;y<=currentYear+3;y++)statsYear.innerHTML+=`<option ${y===currentYear?'selected':''}>${y}</option>`;
function updateStats(){let y=Number(statsYear.value),c={ferie:0,malattia:0,permesso:0};Object.entries(events).forEach(([k,v])=>{if(Number(k.slice(0,4))===y)c[v]++});document.getElementById('vacCount').textContent=c.ferie;document.getElementById('sickCount').textContent=c.malattia;document.getElementById('permCount').textContent=c.permesso;let a=Number(document.getElementById('allowance').value)||0;document.getElementById('remaining').textContent='Ferie rimanenti: '+Math.max(0,a-c.ferie)}
statsYear.onchange=updateStats;document.getElementById('allowance').value=localStorage.getItem('shiftAllowance')||0;document.getElementById('allowance').oninput=e=>{localStorage.setItem('shiftAllowance',e.target.value);updateStats()};updateStats();
